name: cron

on:
  schedule:
    - cron: "00 00 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: update
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun cu.ts
      - name: git setting
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
      - name: Commit files
        run: |
          git add .
          git commit -m "update" -a
          git pull
          git push origin main

